# Define the stages of the pipeline
stages:
  - build
  - deploy

# Define job for building Docker image
build_image:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t jaft/my-node:latest .
    - docker login -u "$user" -p "$pw"
    - docker push jaft/my-node:latest

# Define job for deploying (optional)
deploy:
  stage: deploy
  script:
    # Add deployment commands here
    - ssh $usr@$server #-t "cd /home/ubuntu && bash d.sh"

  only:
    - main  # Only deploy from the main branch (adjust as needed)

