# Define the stages of the pipeline
stages:
  - build
  - deploy
before_script:
- docker login -u jaft -p justafool
- 'which ssh-agent || ( apk add --update openssh git -q )'
- eval $(ssh-agent -s)
- echo "$UB_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -> /dev/null # add ssh key

# Define job for building Docker image
build_image:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t jaft/my-node:latest .
    - docker login -u "$duser" -p "$dpw"
    - docker push jaft/my-node:latest

# Define job for deploying (optional)
deploy:
  stage: deploy
  script:
    # Add deployment commands here
    - ssh "$ubusr"@"$ubserver" -t "cd /home/aungpai && mkdir Git"

  only:
    - main  # Only deploy from the main branch (adjust as needed)

