# Define the stages of the pipeline
stages:
  - build
  - deploy

# Define job for building Docker image
build_image:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t jaft/my-node:Latest .
    - docker login -u jaft -p justafool $CI_REGISTRY
    - docker push jaft/my-node:Latest .

# Define job for deploying (optional)
deploy:
  stage: deploy
  script:
    # Add deployment commands here
    - echo "Deployment script goes here"
  only:
    - main  # Only deploy from the master branch (adjust as needed)

